name: Test RISCV64 on Ubuntu

on:
  pull_request:
    branches: [ main ]

jobs:
  build_job:
    runs-on: ubuntu-22.04
    name: Build on Ubuntu 22.04 RISC-V 64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if rebuild required
        uses: ./.github/actions/check-rebuild
        with:
          mode: rebuild
      - uses: uraimo/run-on-arch-action@v2
        name: RISCV64 Run-on-arch
        if: env.rebuild == '1'
        id: roaa_runcmd
        with:
          arch: riscv64
          distro: ubuntu22.04

          githubToken: ${{ github.token }}

          install: |
            apt-get -qy update
            apt-get -qy install meson ninja-build libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libglib2.0-dev libjson-glib-dev gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good libgtest-dev libpng-dev libopencv-dev python3 python3-dev python3-numpy pkg-config gcc g++ liblua5.1-dev bash wget libpng-dev libopenblas-dev cmake libiniparser-dev libjsoncpp-dev libcurl3-dev
          run: |
            bash .github/workflows/get_ssat.sh
            meson build -Denable-test=true -Denable-tflite-backbone=false -Denable-tflite-interpreter=false -Denable-app=false
            ninja -C build
            pushd build && ninja test
            popd
